// algo-solve-studio/src/components/Navbar.tsx

import { useAuth } from '@/contexts/AuthContext';
import { Button } from '@/components/ui/button';
import { Avatar, AvatarFallback, AvatarImage } from '@/components/ui/avatar';
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator, DropdownMenuTrigger } from '@/components/ui/dropdown-menu';
import { Badge } from '@/components/ui/badge';
import { Link, useLocation } from 'react-router-dom';
import Logo from './Logo';

const Navbar = () => {
  const { user, logout } = useAuth();
  const location = useLocation();

  const isActive = (path: string) => location.pathname === path;

  return (
    <nav className="border-b bg-white/80 backdrop-blur-sm sticky top-0 z-50">
      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="flex justify-between items-center h-16">
          <div className="flex items-center space-x-8">
            <Link to="/" className="flex items-center space-x-2">
              <Logo />
            </Link>
            <div className="hidden md:flex items-center space-x-6">
              <Link
                to="/"
                className={`px-3 py-2 rounded-md text-sm font-medium transition-colors ${
                  isActive('/') ? 'text-blue-600 bg-blue-50' : 'text-gray-700 hover:text-blue-600'
                }`}
              >
                Problems
              </Link>
              <Link
                to="/submissions"
                className={`px-3 py-2 rounded-md text-sm font-medium transition-colors ${
                  isActive('/submissions') ? 'text-blue-600 bg-blue-50' : 'text-gray-700 hover:text-blue-600'
                }`}
              >
                My Submissions
              </Link>
            </div>
          </div>
          <div className="flex items-center space-x-4">
            <Badge variant="secondary" className="hidden sm:flex">
              <span className="w-2 h-2 bg-green-500 rounded-full mr-2"></span>
              12 problems solved
            </Badge>
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant="ghost" className="relative h-10 w-10 rounded-full">
                  <Avatar className="h-10 w-10">
                    <AvatarImage src={user?.avatar} alt={user?.name} />
                    <AvatarFallback className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white">
                      {user?.name?.split(' ').map(n => n[0]).join('')}
                    </AvatarFallback>
                  </Avatar>
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent className="w-56" align="end">
                <div className="flex items-center justify-start gap-2 p-2">
                  <Avatar className="h-8 w-8">
                    <AvatarImage src={user?.avatar} alt={user?.name} />
                    <AvatarFallback className="bg-gradient-to-r from-blue-600 to-indigo-600 text-white text-xs">
                      {user?.name?.split(' ').map(n => n[0]).join('')}
                    </AvatarFallback>
                  </Avatar>
                  <div className="flex flex-col space-y-1">
                    <p className="text-sm font-medium">{user?.name}</p>
                    <p className="text-xs text-muted-foreground">{user?.email}</p>
                  </div>
                </div>
                <DropdownMenuSeparator />
                <DropdownMenuItem asChild>
                  <Link to="/profile">Profile</Link>
                </DropdownMenuItem>
                <DropdownMenuItem asChild>
                  <Link to="/submissions">My Submissions</Link>
                </DropdownMenuItem>
                <DropdownMenuSeparator />
                <DropdownMenuItem onClick={logout} className="text-red-600">
                  Logout
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </div>
    </nav>
  );
};

export default Navbar;

// decode-client/src/lib/components/Navbar.svelte
<script lang="ts">
	import { page } from '$app/stores';

	// Check if current path matches the link
	function isActive(path: string): boolean {
		return $page.url.pathname === path;
	}
</script>

<nav
	class="sticky top-0 z-50 border-b border-white/20 bg-black/95 backdrop-blur-sm"
	style="height: 72px;"
>
	<div class="mx-auto flex h-full max-w-[1353px] items-center justify-between px-4 md:px-16">
		<!-- Logo -->
		<a href="/" class="flex items-center gap-2">
			<div class="flex h-8 w-8 items-center justify-center rounded-full bg-white">
				<span class="text-xs font-bold text-black">D</span>
			</div>
			<span class="text-lg font-bold text-white">DeCode</span>
		</a>

		<!-- Navigation Links - Hidden on mobile -->
		<div class="hidden items-center gap-8 md:flex">
			<a
				href="/problems"
				class="text-sm transition {isActive('/problems') ? 'text-white' : 'text-gray-300 hover:text-white'}"
			>
				Problems
			</a>
			<a
				href="/explore"
				class="text-sm transition {isActive('/explore') ? 'text-white' : 'text-gray-300 hover:text-white'}"
			>
				Explore
			</a>
			<a
				href="/pricing"
				class="text-sm transition {isActive('/pricing') ? 'text-white' : 'text-gray-300 hover:text-white'}"
			>
				Pricing
			</a>
		</div>

		<!-- Auth Buttons -->
		<div class="flex items-center gap-3">
			<a
				href="/login"
				class="rounded-lg border border-gray-600 px-5 py-2.5 text-sm font-medium text-white transition hover:border-gray-400"
			>
				Login
			</a>
			<a
				href="/signup"
				class="rounded-lg bg-primary px-5 py-2.5 text-sm font-medium text-white transition hover:bg-primary/90"
			>
				Sign Up
			</a>
		</div>
	</div>
</nav>
